# Generated by Django 3.2.25 on 2025-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('idV', models.CharField(max_length=1000)),
                ('seq', models.IntegerField()),
                ('formName', models.CharField(max_length=1000)),
                ('eventType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChartPanelCOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('idV', models.CharField(max_length=1000)),
                ('seq', models.IntegerField()),
                ('formName', models.CharField(max_length=1000)),
                ('eventType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GemfireCountTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('countDiff', models.IntegerField()),
                ('hiveCount', models.IntegerField()),
                ('gemfireCount', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GZTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('statts', models.DateTimeField()),
                ('endts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('idV', models.CharField(max_length=1000)),
                ('seq', models.IntegerField()),
                ('formName', models.CharField(max_length=1000)),
                ('eventType', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1000)),
                ('jobName', models.CharField(max_length=1000)),
                ('POC', models.CharField(max_length=1000)),
                ('onBoarding', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lebal', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ReconVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqId', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tblName', models.CharField(max_length=1000)),
                ('pipeline', models.CharField(max_length=1000)),
                ('temporal', models.CharField(max_length=1000)),
                ('onBoarding', models.CharField(max_length=1000)),
                ('batch', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=1000)),
                ('startOffSet', models.CharField(max_length=1000)),
                ('endOffSet', models.CharField(max_length=1000)),
                ('field1', models.CharField(default='test', max_length=1000)),
                ('field2', models.CharField(default='test', max_length=1000)),
                ('field3', models.CharField(default='test', max_length=1000)),
                ('field4', models.CharField(default='test', max_length=1000)),
                ('field5', models.CharField(default='test', max_length=1000)),
                ('field6', models.CharField(default='test', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RequestVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqId', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('reconType', models.CharField(max_length=1000)),
                ('tblName', models.CharField(max_length=1000)),
                ('flow', models.CharField(max_length=1000)),
                ('startOffSet', models.CharField(max_length=1000)),
                ('endOffSet', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('idV', models.CharField(max_length=1000)),
                ('eventType', models.CharField(max_length=1000)),
                ('formName', models.CharField(max_length=1000)),
                ('seq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SKReconTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('mismatchFreq', models.IntegerField()),
                ('mismatchCount', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lebal', models.CharField(max_length=1000)),
                ('isRTTable', models.CharField(max_length=1000)),
            ],
        ),
    ]
