# Generated by Django 5.2 on 2025-04-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JoinKey', models.CharField(max_length=1000)),
                ('FieldName', models.CharField(max_length=1000)),
                ('Kafka', models.CharField(max_length=1000)),
                ('Impala', models.CharField(max_length=1000)),
                ('Gemfire', models.CharField(max_length=1000)),
                ('ReconStatus', models.CharField(max_length=1000)),
                ('RequestID', models.CharField(max_length=1000)),
            ],
        ),
    ]
