# Generated by Django 5.2 on 2025-04-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0002_reconresult'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reconresult',
            table='neuroreconui_reconresult',
        ),
    ]
