# Generated by Django 5.2 on 2025-04-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0004_gemfirecounttable1_env_gemfirecounttable1_tblname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconresult',
            name='FieldName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconresult',
            name='Gemfire',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconresult',
            name='Impala',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconresult',
            name='Kafka',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconresult',
            name='ReconStatus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconresult',
            name='RequestID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reconvo',
            name='field6',
            field=models.CharField(default='InProgress', max_length=1000),
        ),
    ]
