# Generated by Django 5.2 on 2025-04-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0005_alter_reconresult_fieldname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCDVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqId', models.CharField(blank=True, max_length=1000)),
                ('name', models.CharField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.CharField(blank=True, max_length=1000)),
                ('env', models.CharField(blank=True, max_length=1000)),
                ('entity', models.CharField(blank=True, max_length=1000)),
                ('filePath', models.CharField(blank=True, max_length=1000)),
                ('fileType', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
