# Generated by Django 5.2 on 2025-04-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0006_scdvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scdvo',
            name='outputFile',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
