# Generated by Django 5.2 on 2025-04-13 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0007_scdvo_outputfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scdvo',
            old_name='date',
            new_name='status',
        ),
    ]
