# Generated by Django 5.2 on 2025-04-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroReconUI', '0008_rename_date_scdvo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scdvo',
            name='status',
            field=models.CharField(blank=True, default='InProgress', max_length=1000),
        ),
    ]
